- title: You Might Not Need Redux
  description: Come one, come all to the latest thought-leader parade of the week. Do you need Redux... or not?
  author: Dustin Schau
  authorUrl: https://dustinschau.com
  twitter: schaudustin
  published: 2018-02-12T23:36:11.441Z
